### ISSUE TITLE
Speed up travis

### ISSUE THREAD

**Issue by mf59816** [liqd/thentos#14]
http://docs.travis-ci.com/user/caching/

**Comment by fhartwig** [comment]
The stuff in that document is
> only available for private repositories on travis-ci.com
There are [other ways](http://looprecur.com/blog/haskell-types-tests-and-fast-feedback/) to cache the sandboxes, which basically consist of uploading sandboxes to some server and then having travis download it before building. Not sure how feasible this is, given our 650M sandbox (although we can compress it to ~60M). I'm also not sure if this can cause trouble when we update our depencies.
Anyway, it's probably worth doing at some point, but it's not entirely straightforward.

**Comment by mf59816** [comment]
ok.  i didn't really look at the link above, i just got my hopes up real high.  disappointing...

I propose to do this (not necessarily any time soon):

- set up / find a web server that we control.
- write a script (and commit to `./misc/`?) that removes the sandbox, builds it from scratch, compresses .cabal-sandbox, and moves it to a directory where the web server can serve it.  the name of the archive is the hash of the freeze file.
- write code for travis to try and download and uncompress the archive based on the hash of the existing freeze file.  if this fails, just fall back to what we do now and build everything from scratch.

**Comment by mf59816** [comment]
Fixed accidentally in #22
