### ISSUE TITLE
Pretty-print request- and response body samples in docs

### ISSUE THREAD

**Issue by fhartwig** [liqd/thentos#155]
The request body samples in our documentation can be fairly long and are always dumped into a single line. We should pretty print examples where necessary.

**Comment by mf59816** [comment]
`s/where necessary/by default/`.  This will probably be a patch for `servant-docs`?

**Comment by mf59816** [comment]
note the related FIXME in `Thentos/Backend/Api/Docs/Common.hs`, line 48.

**Comment by mf59816** [comment]
I looked into this a bit.  The rendering functions that are used are defined in the instance of class 'MimeRender` from `Servant.API.ContentTypes`.  Those are not intended for pretty-printing.

It is straight-forward enough to parse and re-encode the strings from servant-docs `API`, though.  Do something like this in `Thentos.Backend.Api.Docs.Common`:

```haskell
prettyMimeRender' :: [(M.MimeType, SBS -> SBS)] -> API -> API
prettyMimeRender' = _

prettyMimeRender = prettyMimeRender [("application/json",
                                      Aeson.encode . fromJust . Aeson.decode)]
```

Then we can call `prettyMimeRender` in `exec/BuildDocs.hs`.

(Don't use `fromJust`!  :-]  But it's ok to throw an internal error if this fails.)
