### ISSUE TITLE
A3 API: Handle User Password reset

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#168]
The A3 backend implements an endpoint that allows resetting the passwords of users, see the last section of https://github.com/liqd/adhocracy3.mercator/blob/master/src/adhocracy_core/docs/authentication_api.rst. Our A3 compatibility API doesn't yet. We won't need that for SSO, but sooner or later we'll need it for full compatibility with the A3 frontend.

**Comment by mf59816** [comment]
Agreed.

We already have that in `Backend.Api.Simple` or in `Frontend.*`.  Possibly relevant exports from `Action`:

```haskell
module Thentos.Action
    ( ...
    , addPasswordResetToken
    , resetPassword
    , changePassword
    , requestUserEmailChange
    , confirmUserEmailChange
    , updateUserField, T.UpdateUserFieldOp(..)
    , updateUserFields
    ....
```
