### ISSUE TITLE
Fix proxy config type.

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#194]
The config type for http proxies looks like this:

```haskell
type ProxyConfig' =
            ("service_id" :> ST)
  :*>       ("http"       :> HttpConfig')
  :*> Maybe ("url_prefix" :> ST)

type HttpConfig' =
      Maybe ("bind_schema"   :> HttpSchema)
  :*>       ("bind_host"     :> ST)
  :*>       ("bind_port"     :> Int)
  :*> Maybe ("expose_schema" :> HttpSchema)
  :*> Maybe ("expose_host"   :> ST)
  :*> Maybe ("expose_port"   :> Int)
```

`HttpConfig'` makes sense for listeners, but not for clients (for a client, there is only the exposed side of the server).  In `ProxyConfig'`, it is used client-side.

The requirement to be implemented is that `ProxyConfig'` should not contain information about both an exposed and a bind host.

Proposal: leave `ProxyConfig'` as is, but do this (pseudo-code):

```haskell
type HttpConfig' =
      Maybe ("schema" :> HttpSchema)
  :*> Maybe ("host"   :> ST)
  :*>       ("port"   :> Int)

type HttpServerConfig' =
      Maybe ("bind"   :> HttpConfig)
  :*> Maybe ("expose" :> HttpConfig)
```

Alternative with uri-bytestring:

```haskell
type ProxyConfig' =
            ("service_id" :> ST)
  :*>       ("http"       :> URL)
  :*> Maybe ("url_prefix" :> ST)

type HttpServerConfig' =
      Maybe ("bind"   :> URL)
  :*> Maybe ("expose" :> URL)
```

One weirdness about the second approach is that `URL` may contain more information than can be processed here, so I prefer the slightly more awkward, first proposal.

**Comment by fisx** [comment]
oops: this is a duplicate of #174.

**Comment by ChristianSi** [comment]
Closed as duplicate.
