### ISSUE TITLE
Make handling of polymorphic errors more safe.

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#207]
In response to https://github.com/liqd/thentos/pull/198#discussion-diff-34512981, I just tried to change `Extends` along these lines:

```haskell
-    thentosErrorFromParent :: ThentosError dbParent -> ThentosError dbChild
-    -- ^ If a transaction or action associated with 'dbParent' throws an error, use
-    -- this function to convert it to an error that can be thrown by
-    -- transactions or actions associated with @dbChild@.
+    thentosErrorThrowParent :: ThentosError dbParent -> mChild a
+    -- ^ Use this to throw an error in transactions or actions associated with @dbChild@.
 
-    thentosErrorToParent :: ThentosError dbChild -> Maybe (ThentosError dbParent)
-    -- ^ Use this to catch an error thrown by a polymorphic transaction.
+    thentosErrorCatchParent :: mChild a -> (ThentosError dbParent -> mChild a) -> mChild a
+    -- ^ Counterpart of 'thentosErrorThrowParent'.
```

Some obvious problems:

1. we now have a type variable `mChild` not caught by the class.
2. we seem to duplicate `MonadError`.  perhaps there is a way to use it instead?  Instantiate `MonadError (ThentosError parent) (Action child a)`, or something?

Apart from that, I think this is the right approach.

**Comment by fisx** [comment]
@robx: you can take this one.  before you do, you probably want to read docs/concepts/AcidPoly.lhs and then ask questions.  it would be great if you could write down any insights that hit you on the way and add them to docs/* or the README.

**Comment by fisx** [comment]
probably relevant: `2015-07-22-mf-fix-weirdness-in-action-helper`

**Comment by fisx** [comment]
this ticket will look very different once #268 is closed!  close?  or wait until it's clear it doesn't apply any more?

**Comment by robx** [comment]
Let's close this, it's obsoleted by changes in https://github.com/liqd/thentos/pull/281.
