### ISSUE TITLE
Better proxying

### ISSUE THREAD

**Issue by jkarni** [liqd/thentos#224]
Looking at https://github.com/liqd/thentos/blob/master/thentos-core/src/Thentos/Backend/Api/Proxy.hs#L49, it seems to me like our proxying isn't optimal. For one, it seems to me like we might get space leaks. Maybe it's worth investigating whether in fact this is the case, but we could also just use an existing soution (such as [this](https://hackage.haskell.org/package/http-reverse-proxy-0.4.2/docs/Network-HTTP-ReverseProxy.html#g:2) ).

**Comment by jkarni** [comment]
We are also using `withManager`, and so creating a new manager on each request, which the documentation says is a bad idea.

**Comment by fisx** [comment]
is this done?  (which pr?)

**Comment by jkarni** [comment]
Done in #241
