### ISSUE TITLE
404 logging out from helloworld

### ISSUE THREAD

**Issue by robx** [liqd/thentos#231]
logged in successfully as god/god, the clicked logout:

```
A web handler threw an exception. Details:
*** StatusCodeException
  Status { statusCode = 404 , statusMessage = "Not Found" }
  [ ( "Transfer-Encoding" , "chunked" )
  , ( "Date" , "Fri, 17 Jul 2015 15:48:39 GMT" )
  , ( "Server" , "Warp/3.0.13.1" )
  , ( "X-Response-Body-Start" , "thentos session not found" )
  , ( "X-Request-URL"
    , "DELETE http://localhost:7001/service_session/"
    )
  ]
  CJ { expose = [] }
```

**Comment by fisx** [comment]
I tried to fix other errors before, and ended up doing this:

78eda72327d6d174cfcdd29ea5d43239e1d9ed21

...  which lead to further errors, which led me to believe that there may be something wrong with the label passed to `runAction` in some handler.

This is where I got distracted.  Anyway, it's not entirely implausible that the lio policy is not bug-free yet.

**Comment by fisx** [comment]
(further reading: #77)

**Comment by fisx** [comment]
related: #228.
