### ISSUE TITLE
Clean up test infrastructure

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#238]
`setupBare` in `Thentos.Test.Core` returns a config structure rather than accepting one (or better yet, accepting the name of a config file).  By inheritance, so do `setupDB`, `setupTestBackend`, and `setupTestServerFull`.

1. In `Thentos.Test.Config`, make `TestConfig` a configifier type that contains `ThentosConfig` as a sub-structure.  (Merging the two would be possible, but I think it would be less convenient if we need to pass a `ThentosConfig`, and not any sub-type, to the tested code.)
1. Move the inlined config data from `Thentos.Test.Config` to a file.
1. Change the `setup*` functions so that they accept a filename that they import the config from.

There may be even a better plan.  Whoever works on this: feel free to suggest improved plans.

**Comment by jkarni** [comment]
Cf. #273.

**Comment by jkarni** [comment]
Done in #273. Re: (2) and (3) - I used a QQ instead of files
