### ISSUE TITLE
Don't build hlint on travis

### ISSUE THREAD

**Issue by fhartwig** [liqd/thentos#242]
Travis currently takes a long time to run. One of the problems is that we build hlint (including its dependencies) on every build. Since hlint depends on haskell-src-exts, which takes forever to build, this slows our build quite a bit.
I'm personally not convinced that we need to run hlint on travis, but even if we do, we should make sure it doesn't make our build take longer than necessary.

**Comment by jkarni** [comment]
Ouch - 10 min! I never much liked `hlint`, so I'm +1 on this, though just downloading the built executable would also certainly be an improvement.

**Comment by fisx** [comment]
I would like hlint to keep running on travis.  Install hvr-binary?  It is possible that that version is too old for our `HLint.hs` files, but we may be lucky.

**Comment by fhartwig** [comment]
@fisx hvr's ubuntu ppa doesn't seem to have hlint. I can build a binary that works on travis in the vm and then upload that so travis can just wget it. Unlike our old sandbox, that should require very little maintenance.

**Comment by fisx** [comment]
@fhartwig: sounds good.  where would you upload it?  i guess we could use the github cache we already have?  feel free to grab this ticket and do it next.

**Comment by jkarni** [comment]
Can't we just use a git commit hook?

**Comment by fisx** [comment]
git commit hooks are only for the patient.  (-:

i just checked, and it's *almost* tolerably fast.  but then there is still the risk of people disabeling it.  i'd prefer if travis did it.

**Comment by jkarni** [comment]
You've made sure only the dirty files are being checked?

**Comment by fisx** [comment]
ah.  no.  that may be fast enough.  that would leave the "people can turn it off" argument.

i won't change my preference, but i guess i can live with either solution.
