### ISSUE TITLE
Refactor type `ProxyUri`.

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#246]
In some offline discussion recently we agreed to keep the URI parsers for proxy endpoints, and wrap them with a newtype to enforce additional constraints (no query, port always present, possibly others).  This would have the welcome effect that we can map the public URI `http://somehwere/user/0` to `localhost:7891/api/v3.1/user/0`, because we could allow prefixes (which are currently gone from the config).

Also, there is a missing empty line at the end of the uri haddock section in `Thentos.Types`.

**Comment by jkarni** [comment]
See #253. Not a newtype-wrapped `URI`, since that would still mean all the pain of `fromJust`s etc., but does use the `URI` parser.

**Comment by fisx** [comment]
fixed in #253
