### ISSUE TITLE
Add personas to data model in core.

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#255]
One off-the-top-of-my-head implementation:

```haskell
data User = User { ... ; userPersonas :: Map ServiceId UserName }
```

Now two services know the same user under different names, and if there are no other details being passed to the service (like an identifying email address, the actual user name, or user id), the owner of service1 won't be able to see what their local users publicly do on service2 (because on service2 they have a different name).

This may be a requirement for a deadline later this year.  We should start work on this by writing more pseudo-code and thinking about the apis.

**Comment by fisx** [comment]
More detailed requirements:

1. pseudonyms can be either generated at random or chosen by the user.
1. the pseudonym can be allowed to be reused for different services or forbidden ("freshness" constraint).
1. the service can be configured to fix all the above options (e.g.: only accept random pseudonyms to avoid informatoin leakage through pseudonyms that look like the real name).  in particular, the service should probably force thentos to not reveal anything *but* a pseudonym, if pseudonyms are desired in the first place.

**Comment by ChristianSi** [comment]
We now have personas and contexts.
