### ISSUE TITLE
Return proper error responses

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#274]
Currently Thentos doesn't return proper HTTP replies in case of errors. There are two problems:

* No Content-Type header is set.
* The response body is just a naked error string.

E.g. to reproduce: start thentos-adhocracy and call

    curl -v -H 'X-User-Token: blah: blah' http://localhost:6546/

The response body will be "thentos session not found" without a Content-Type header.

The most simple, but hardly satisfying way would to be to add "Content-Type: text/plain" in case of errors. Then returning a naked error message would at at least result in a proper HTTP response.

But since the rest of the API is JSON, instead setting "Content-Type: application/json; charset=UTF-8" and wrapping the error message into a simple JSON object would probably be a better approach.
For example (somewhat similar to A3 error messages):

    {"status":"error", "error": "thentos session not found"}

Or (even simpler):

    {"error": "thentos session not found"}

In the case of the error situation mentioned here as example it's also confusing that the response code is HTTP/1.1 404 Not Found. It should rather be something like 403 Forbidden. But that's a detail for that specific error.

@fisx @jkarni @fhartwig @robx I'd like to hear your input on how to handle errors.

**Comment by fhartwig** [comment]
I agree that it makes sense to return errors as JSON (no opinion on the specific format). I also agree that the status codes that we currently return are mostly nonsense. These changes should be fairly straightforward. I think we just need to adapt the relevant `ThentosErrorToServantErr` instances.

This raises the question if the error-conversion code should be moved from `thentos-core` into the specific packages. But I think this isn't necessary yet, we can still to it later if that becomes necessary.

**Comment by ChristianSi** [comment]
Unless someone protests, I'll implement this returning a two-field JSON object for now:

    {"status":"error", "error": "..."}

The details of the JSON object can still easily be changed later, if desired.

**Comment by jkarni** [comment]
@ChristianSi you probably know much more about this than I do, but from the few A3 endpoints that I saw, the error objects has a list of errors (rather than just a string). Maybe keeping it that way makes sense?

**Comment by ChristianSi** [comment]
This is, for now, more about what makes sense *for us* regardless of what A3 needs. I agree that maybe it makes sense to change the error objects returned by thentos-adhocracy  to make them more similar to those returned by the A3 backend. But for thentos-core I think that a single "error" makes more sense since we always have only one error.

**Comment by jkarni** [comment]
Ok. I don't know about 401 vs. 403 in this case. If the session just expired, we probably shouldn't be sending a 403. But I don't know.

**Comment by ChristianSi** [comment]
The point is that "session not found" should NOT be 404 since that implied that the endpoint does not exist rather than that the user is not properly authenticated.

**Comment by jkarni** [comment]
Right, I agree.
