### ISSUE TITLE
Thentos proxy: handle user activation properly

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#283]
Right now user activation in A3 is turned off if it runs behind a Thentos proxy. In A3, all created users are immediately considered active. Thentos sends the activation email and activates the account after the user has clicked on a link.

This is not a good solution since only active users are visible and listed, and if somebody tries to access a not-yet-activated user, they get an error response (410 Gone). By activating all users immediately (in A3), the Thentos proxy bypasses these privacy settings.

To fix this, we should activate users in A3 at the same time as in Thentos. The most simple solution to do that seems to be:

* Let A3 send activation emails rather than do it in Thentos. This also has the advantage that A3 defines templates that make it easy to change the subject and contents of these emails, while in Thentos they are currently hardcoded.
* If the user clicks on an activation link, rather then handling the activation completely in Thentos, forward the request to A3 which will respond with 200 or an error. If 200, activate the user in Thentos too. (The response sent by A3 reveals which user was just activate). Then forward the response to the client.

**Comment by jkarni** [comment]
This sounds good. Are we okay with A3 having email addresses, and all user info, though?

**Comment by ChristianSi** [comment]
For the time being, A3 gets the email address anyway. Other user info it only gets if we pass it through -- currently that's the case for user name, but not for the password.

But it's a good point, if we decide to store the email address in Thentos only, then the suggested approach won't work any more. For the time being, it nevertheless seems the most simple approach but we should keep in mind that we might need another approach later.
