### ISSUE TITLE
Internal errors must not leak details to the client

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#291]
When calling thentos-adhocracy when A3 is not running, I not get a response with status code 502 Bad Gateway, content-type: text/plain and the following content:

    Error connecting to gateway:
    
    FailedConnectionException2 "localhost" 6541 False connect: does not exist (Connection refused)

This is new behavior, I suppose that @jkarni introduced it during some refactoring?

It it undesirable in various ways:

* All server-side errors should be returned as 500 Internal Server Error, status codes higher than 500 should *never* be returned.
* Also, the request body should only contain a generic "internal error" message without leaking *any* details about what went wrong to the client. Such details should only be written into the log.
* The response body Content-Type should be `application/json` and the body should be a JSON object. I thought that all our errors were automatically converted into the expected format, I don't know how this one manages to slip through. 

FYI @fisx, @jkarni

**Comment by jkarni** [comment]
It may very well be this was caused by my change. I agree leaking information is bad, and that we should have a JSON error. If it doesn't break the client, I'd prefer to have the right HTTP status code (502), but it sounds like it does break the client?

**Comment by ChristianSi** [comment]
I don't think the A3 frontend specifically cares about the status code; when it gets a reply it doesn't understand and cannot properly handle, it will just display a generic "something went wrong" message.

*But* I'm strongly opposed to leaking internal state to the outside world. That we're even running in proxy mode is purely an implementation detail and of no concern to the client, therefore we should never throw a "502 Bad Gateway" error -- that would only make sense if the client knew they're talking to  a proxy and could somehow deal with proxy errors (say by turning the proxy off). In our case that's clearly not the case.

The same kind of reasoning applies to all other 5xx errors where xx != 00: such errors would leak internal state and must therefore *never* be thrown. Hence, all irrecoverable/internal errors *must* lead to "500 Internal Server Error" rather than anything else. Also, the response body of all status 500 replies *must* be identical rather than leaking internal state about what exactly went wrong -- such information belongs in the log but must not be leaked to the client.

AFAIK, prior to our refactoring, our error handling worked the way I've just described it. Your refactoring apparently broke that behavior which is not a good thing. We should restore the original behavior.
