### ISSUE TITLE
Group management

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#319]
Groups can be assigned to personas. Groups are (probably) just strings. There is a Role that is required for assigning and un-assigning groups. Personas and groups can be assigned to groups. Re-activate the function that flattens all groups to which a persona belongs (either directly or indirectly through another group). Cf. existing GroupNode data structure which might need a thorough rewrite.

**Comment by fisx** [comment]
For a group rewrite, this might work:

```haskell
newtype Group = Group { fromGroup :: ST }

data GroupMember =
        GroupG { fromGroupG :: Group }
      | GroupU { fromGroupU :: UserId }

type GroupTree = Map GroupMember [Group]

inviteUser :: GroupTree -> UserId -> Group -> GroupTree
inviteGroup :: GroupTree -> Group -> Group -> GroupTree
memberShips :: GroupTree -> GroupMember -> [Group]

data Service =
    Service
      { ...
      , _serviceMemberships :: GroupTree
      , ...
      }
```

The thing I'm least sure about is the `Map`; there may be something with better complexity (or at least with better constants).

@ChristianSi, I think in our current mental model of things, you may want to leave services group-unaware and rather attach membership maps to processes, which are their own data type.  Let's see if it stays that way.  :-)

**Comment by ChristianSi** [comment]
Note: only personas (and other groups) can be group members, users never.
