### ISSUE TITLE
Change user activation process

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#320]
Users are activated by Thentos, independently from A3. A confirmed user can only log into A3 using a persona. If the persona is used for the first time, a new A3 user is created that has the persona name as name. The user's email address is either empty (requires changes in A3) or set to some unique random values. Neither the actual name nor email of the user are ever exposed to A3.

Handle and store the mapping from A3 user names/paths to persona names. Note: For the beginning we'll probably work with a global A3 user management rather than process-specific users.

**Comment by fisx** [comment]
backend + frontend?
