### ISSUE TITLE
Build a widget in a form suitable for using from angular.

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#326]
angular is quite flexible, so we should use what works best for us, and then interface into angular.

options:
- https://github.com/slamdata/purescript-halogen (my preference)
- https://github.com/purescript-contrib/purescript-react
- https://github.com/paf31/purescript-thermite
- things i missed?

I played a bit with thermite and ran into an error that seemed hard to fix, and likely to be located either in thermite or in the underlying react binding (or, a lot less likely, in [react](https://facebook.github.io/react/) itself).

Atlassian is [using halogen](http://cufp.org/2015/t10-brian-mckenna-pure-script.html) and is quite happy with it, and when I talked to brian he gave the impression that the things we are planning to do are quite trivial compared to what he's already done or seen.

**Comment by jkarni** [comment]
From the links, it seems like we are aiming to build the login form ourselves. This makes it difficult to style the html/css in a way suitable for the specific frontend. Maybe we should consider instead either (a) providing a function that can be easily used as an `onclick` even on the form, or (b) writing a function that when called (after the DOM has loaded) searches for forms of a specific class and adds onclick callback events to them. (I think (a) makes more sense, but in any case (b) involves basically doing (a) first.) @fisx any thoughts?

**Comment by fisx** [comment]
I don't see a lot of appeal in (b), and (a) is essentially #325.  After a quick off-line discussion, we agreed to do #325 first and then re-visit this ticket with more experience.

**Comment by fisx** [comment]
Candidates for widgets:

- login button (aka indicator button)
- something with a big form
- something flashy

**Comment by fisx** [comment]
(see #360)

**Comment by fisx** [comment]
closed in #376
