### ISSUE TITLE
Make Service non-hierarchical.

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#332]
About our earlier off-line discussion on ServiceId, hierarchical services, and agents:

1. I think giving serviceOwner type `UserId` instead of `Agent` makes sense.

1. Agent is also used as Session owner, which is a concept that is more extensively used in the thentos-as-a-server code.  We want to be able to, but not forced to, distinguish between services and users that connect to a rest api.  I don't think we should reomve the `Agent` type.

Does this make sense?  Any objections?

**Comment by jkarni** [comment]
> We want to be able to, but not forced to, distinguish between services and users that connect to a rest api.

What is the distinction? I imagine we're not talking about users in the login sense?

**Comment by ChristianSi** [comment]
I agree to both points from @fisx's comment.

**Comment by fisx** [comment]
@jkarni: sorry, I didn't see your question.  The distinction is that services have different needs than users when they are logging into thentos.  A user may login to get access to a service; a service may login to query user properties, or to register a context.

Does that explain it?
