### ISSUE TITLE
Remove Service Sessions

### ISSUE THREAD

**Issue by jkarni** [liqd/thentos#333]
Services would have an easier time just sending their credentials on each request.
We also don't need to hash their password since they are randomly generated.

**Comment by fisx** [comment]
I agreed to that earlier, but I changed my mind.  From the first paragraph of the [scrypt paper](http://www.tarsnap.com/scrypt/scrypt.pdf):

> Password-based key derivation functions are used [...] to hash passwords so that an attacker who gains access to a password file does not immediately possess the passwords contained therewithin [...]

So if we use scrypt for service keys, losing a postgresql dump to an attacker won't leak them; if we don't, it will.

I still think it's worth looking into this, but there is a very good reason that we are using scrypt now.

**Comment by ChristianSi** [comment]
I agree with @fisx, it makes sense to keep them.

**Comment by ChristianSi** [comment]
Maybe we should close this ticket?

**Comment by fisx** [comment]
(if anybody can think of new arguments or evidence: please to re-open and add it!)
