### ISSUE TITLE
GC

### ISSUE THREAD

**Issue by mf59816** [liqd/thentos#34]
1. implement `trans_garbageCollectSessions`.
2. write analogues for `_dbUnconfirmedUsers, _dbPwResetTokens, _dbEmailChangeTokens`.
3. write action that collects all expired items in all four maps, and calls the four resp. transactions.
4. wrap in a function that calls gc periodically.  call at start time.  read period from configifier ('Nothing' means never gc).

consider doing this in several (4?) separate pull requests.

**Comment by fhartwig** [comment]
Implemented in 24609d52e438c833396a44618742b40a74309d66
