### ISSUE TITLE
Create document defining the user management terms

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#366]
Such as role, group, permission, etc.

Should be reviewed by everybody interested in thentos / adhocracy teams

**Comment by fisx** [comment]
(also handling persona here)

**Comment by fisx** [comment]
Link to the draft (self-updating): https://github.com/liqd/thentos/blob/2015-10-29-mf-terminology/docs/terminology.md

**Comment by fisx** [comment]
I wrote down everything I could think of that fits into this document.  Ready for disucssion in both teams, IMO.
