### ISSUE TITLE
Fix user handling bug on the thentos + a3 staging server

### ISSUE THREAD

**Issue by fhartwig** [liqd/thentos#367]
On the staging server, we get 400 errors when we try to log into a3. I thought I had fixed this in https://github.com/liqd/adhocracy3.mercator/pull/1778 but @ChristianSi  pointed out that the "fix" was only hiding / moving the bug. We need to figure out what exactly goes wrong and fix it in a3.

**Comment by fisx** [comment]
See also: https://github.com/liqd/adhocracy3.mercator/issues/1797

**Comment by fisx** [comment]
See also: https://github.com/liqd/adhocracy3.mercator/pull/1798

@fhartwig: can you close this or explain why it is still open?  (please also update corresponding taiga task)

**Comment by fhartwig** [comment]
This was still open because it was waiting for https://github.com/liqd/adhocracy3.mercator/pull/1798 to be merged.
