### ISSUE TITLE
Make websockets work on staging server

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#369]
A3 backend must run without logging errors and the frontend must by able to subscribe to websocket notifications and get then. Thentos shouldn't be involved here, i.e. websocket connections are directly between A3 frontend and backend.

May require help from the admin team to configure nginx etc. correctly.

**Comment by fisx** [comment]
help for nginx config is indeed required.  on the other hand, i think the only consequence of not having web sockets is that some things won't change in the UI until the user hits reload.  everything should be quite presentable without.

i move to close this ticket.

**Comment by ChristianSi** [comment]
I'm against closing this. The staging server should have a fully working A3 installation, which includes websockets.

**Comment by fisx** [comment]
(moving to taiga internal wiki)
