### ISSUE TITLE
write definition of done

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#373]

**Comment by fisx** [comment]
@rittermo, is this done?

**Comment by rittermo** [comment]
@fisx No, it was just badly neglected by me. 

I put a draft of the Definition of Done and the Definition of Ready in our Taiga wiki and would like to discuss them with the team next Wednesday.

**Comment by rittermo** [comment]
Both definitions were discussed on Nov. 19 with the team and can now be considered done.
