### ISSUE TITLE
add "or later" to AGPLv3

### ISSUE THREAD

**Issue by wolftune** [liqd/thentos#392]
As it maximizes compatibility while still maintaining all the protections of AGPL, including the "or later version" (a.k.a. AGPLv3+) doesn't matter at the moment as there's no later version, but it would be preferable still so that the maximum compatibility is assured in the long term, and may be easier to just have now than to try to get agreement to add the clause years down the line or something…

**Comment by ChristianSi** [comment]
I agree :+1:

**Comment by fisx** [comment]
good point.  i'll fix this soon.  sorry for the late reaction.

thanks!

**Comment by fisx** [comment]
@wolftune, does #393 work for you?  The LICENSE files in the cabal are still v3 but the cabal file say "or later", not sure if I like this small inconsistency.  If you have anything you'd like us to change still, I'dl like to hear it.

**Comment by fisx** [comment]
Entertainingly, cabal dislikes the new license, and AGPL-3+ doesn't appear to be in the list of accepted licenses either.

Any suggestions?

**Comment by wolftune** [comment]
Yeah, it's annoying about cabal not accepting the or-later qualification.

I suggest:

A. the LICENSE file in the top level should just take the text from the suggested how-to-apply section of AGPL, namely:

```
    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

That's better than just the simple name of the license in the file.

B. Consider using that for every case where you want to bother mentioning the license, such as in the subdirectories, and include a full copy of the AGPLv3 in the root and link to it from these shorter notices

C. For cabal, I think just `AGPL` is the best option as by not specifying a version, it will apply to any version, and no pre-v-3 really exists anyway

**Comment by nidico** [comment]
@wolftune's suggestion sounds reasonable to me. We should do the same in liqd/adhocracy3 btw.

**Comment by wolftune** [comment]
I was thinking of ignoring this, but to be 100% fair, the *ideal* is to check with all copyright holders of the *current* code and just verify that they all accept the new licensing…

**Comment by fisx** [comment]
No, I like it that you are thorough.  :-)

I don't think there are any besides liquid democracy, though.  All work on this project has either been paid for or done by me, or both.  Do you know something I don't?

**Comment by fisx** [comment]
(I can't speak for https://github.com/liqd/adhocracy3/issues/1856, though.  @nidico?)

**Comment by wolftune** [comment]
I don't know of any other copyright holders, aren't familiar with the history of the project. I'm just excited that there's another fully-free/libre/open co-op democracy focused Haskell-based thing besides my project [Snowdrift.coop](https://snowdrift.coop/) (and specifically one that looks great and useful to us!). In *our* case, if we had to make a license change (we already use AGPLv3+ though), we have maybe 20 or so contributors we'd have to check with for formal approval.

Although some people go further with it, I'm quite sure that people submitting pull requests that already include the unchanged licence stuff is enough to consider that their submissions are under the same license.
