### ISSUE TITLE
allow_ips (privileged-IP check) doesn't support IPv6

### ISSUE THREAD

**Issue by ChristianSi** [liqd/thentos#455]
The thentos config has a "allow_ips" field that can be used to list privileged IP addresses that are authorized to perform some actions not available from other IP addresses. Currently, allowedIps is a `[HostAddress]`, that is, only IPv4 addresses can be listed.

To make this generally usable, we should instead define and use a
sum type that accepts both `HostAddress` and `HostAddress6`. Then we can resolve the FIXME  in `thentos/thentos-core/src/Thentos/Backend/Core.hs` to related to `SockAddrInet6` by checking whether that address is privileged.

**Comment by fisx** [comment]
Fixed in #469.

(@np: if you add the string: `Fixes #<issue number>` into the description of a PR, merging will auto-close the issue.)
