### ISSUE TITLE
Sending emails through Thentos

### ISSUE THREAD

**Issue by np** [liqd/thentos#472]
A new API endpoint should allow services to send emails to users.

Sending an email takes the following fields:

* recipient (email address, pseudonym)
* subject
* plain text body
* optional HTML body

Where to put this endpoint? Under service/ at the root?

**Comment by fisx** [comment]
> Where to put this endpoint? Under service/ at the root?

A service in thentos is a web app that uses thentos for identity management, like adhocracy.  Our data model anticipates many services for one instance, and `/service` is the sub-tree of the api that allows CRUDding them.

What about this `/email`?

**Comment by np** [comment]
`/email` as a group and then `/email/send` or just `/email`?

**Comment by fisx** [comment]
both good.  `/email/send` is more explicit, but i also like the approach of using http verbs to distinguish different things to do under one end point.

what else would there be besides `/email/send`?

**Comment by np** [comment]
I'm now convinced that a `POST` request `/email` is enough.

**Comment by fisx** [comment]
Fixed in #473.
