### ISSUE TITLE
Refactoring: Add a Thentos.Prelude module to capture some essential imports 

### ISSUE THREAD

**Issue by np** [liqd/thentos#482]
I wonder how you feel about such a change?

For instance in Ling you can see https://github.com/np/ling/blob/master/Ling/Prelude.hs

**Comment by fisx** [comment]
Personally I don't feel a strong need for it, but I can't think of any disadvantages (everybody is still free to ignore the Prelude module), so as long as at least one stake holder is in favor of it (which would be you), I'm in!

Do you want to write the PR?

**Comment by fisx** [comment]
I also note that link follows the much more common convention of interleaving qualified and non-qualified imports.  Should we make either choice binding in the style guide?  Which one?

**Comment by fisx** [comment]
I think this is done.  Please re-open if not.
