### ISSUE TITLE
Eliminate code redundancy between formH, formRedirectH in Servant.Missing

### ISSUE THREAD

**Issue by fisx** [liqd/thentos#494]
The constraint of `formRedirectH` implies `MonadError ServantErr`, whereas the type that would be expected everywhere else in thentos is `MonadError (ThentosError a)` for some `a`.

This code should ultimately go to a package `thentos-digestive-functors`, or `servant-digestive-functors`, and in either case allow for arbitrary custom errors.

**Comment by np** [comment]
Apart from your comment about `ThentosError` vs `ServantErr`, PR #501 fixes that.
