### ISSUE TITLE
Pattern match failure in thentos-install

### ISSUE THREAD

**Issue by andorp** [liqd/thentos#497]
From https://travis-ci.org/liqd/aula-docker/builds/110821174#L1408

````
thentos-install.hs: user error (Pattern match failure in do expression at misc/thentos-install.hs:45:5-15)
````

**Comment by andorp** [comment]
Sorry for the noise, I found its reason.

````
ExitSuccess <- runCabal args "--dependencies-only"
````

**Comment by fisx** [comment]
Ok, but what was the reason?  Has it been resolved?

Thanks!

**Comment by andorp** [comment]
Cabal wanted to reinstall packages. Nothing serious.
