### ISSUE TITLE
User always has to register with service when trying to log into it after logging out

### ISSUE THREAD

**Issue by fhartwig** [liqd/thentos#53]
After the following sequence:
* log into thentos frontend
* go to hello-world service
* click on "login"
* click on "register" on thentos register-with-service page
* log out of thentos frontend
* log back into thentos frontend
* go to hw-service, click "login"

we end up on the register-with-service page again. This we should probably get a log-into-service page instead.

**Comment by fhartwig** [comment]
I'm looking into this.

**Comment by mf59816** [comment]
I agree: you should always see "login", and find a link to get to the registration page from there.  I just didn't think this through when I implemented it.

**Comment by fhartwig** [comment]
@mf59816 I agree (I think), but that's a separate issue from this one. I'll make a new ticket for that.
