### ISSUE TITLE
User should have to confirm service login with thentos

### ISSUE THREAD

**Issue by fhartwig** [liqd/thentos#55]
After the following sequence:

* user logs into thentos
* user goes to hello-world service
* user clicks on "login"

the user is automatically logged into the hw-service without having to confirm the login on thentos (if they are already registered with the service). There probably should be some sort of confirmation with thentos before logging the user in.

**Comment by mf59816** [comment]
Feature!  (-:

Facebook does it like this, too.

It's possible that we want to change the behavior as you suggest in the future, but as discussed off-line we will leave it as is for now.
