### ISSUE TITLE
Make template haskell transaction handling less awkward

### ISSUE THREAD

**Issue by fhartwig** [liqd/thentos#72]
We currently need to make multiple template haskell calls to make our transactions acidic (and so do library users). This is because, if we put the generation of our boilerplate functions (currently called `makeThentosAcidicPhase1`) and `makeAcidic` from acid-state in the same splice, template haskell complains that `‘foo’ is not in scope at a reify` (where foo is the first name in the transactions list). It would be nice if we could somehow do all of this in a single splice.

Doing this in a single splice would also allow us to get rid of the `Thentos.Transaction.Transactions` module. This module currently only exists because we cannot put the definition and usage of the `transactionNames` list in the same module because of TH phase restrictions.

**Comment by fisx** [comment]
this has been obsoleted with the removal of acid-state.
