### ISSUE TITLE
Polymorphism over DB

### ISSUE THREAD

**Issue by mf59816** [liqd/thentos#75]
#74 introduces polymorphism over the `DB` type for transactions and actions.  But there are several places where the type gets materialized back into `DB` where we don't want that.

The culprit is `makeAcidic`.  It takes a concrete type `DB`, and not a type variable  After the transactions have thus been frozen back into monomorphicness, actions cannot unfreeze them.  Consider module `Thentos.Action.Core`: `update'P` and `query'P` are not the problem, they don't even need the constraint on the polymorphic `db` variable.  But once the actual frozen transaction is passed to it, the action type is frozen as well.  And everything becomes `DB` again.

I wrote this during a well-typed review telco on 2015-04-15:
 
    then how do we abstract over actions?  `makeThentosAcidic` (or whatever it is called)
    could construct a type class and instance that contains all the transactions it constructs,
    and somebody else could come and overload it.  then actions could use the class instead
    of the concrete types.

This may work, but obviously needs more thinking.

**Comment by mf59816** [comment]
based on a discussion with @robx, i tried this: 

- https://github.com/liqd/thentos/tree/2015-05-26-mf-trans-polymorphism-tweak
- https://github.com/liqd/thentos/compare/2015-05-26-mf-trans-polymorphism-tweak

this looks like a nice improvement, but I don't have time to look deeper into it today.

**Comment by mf59816** [comment]
(#143 does not solve the problem of polymorphic `Action`s, but it does explain a lot about how it may be done.  next steps: write polymorphic `Action`s based on code added manually (without TH) to `Thentos.Transaction`; then generate manually added code with TH.)

**Comment by mf59816** [comment]
```haskell
----------------------------------------------------------------------
-- the upstream library does this:

-- to be generated by @$(makeHasAcidicClass ''DB transaction_names)@ (or
-- is it easier to pass 'AsDB also / instead?)
class (AsDB db) => HasDB db where
    lookupUser :: UserId -> Query db (Either ThentosError (UserId, User))
    -- ...

-- to be generated by @$(makeHasAcidicInstance ''DB transaction_names)@
instance HasDB DB where
    lookupUser = polyQuery . lookupUser
    -- ...

-- then, we can write polymorphic actions:
bumpSession :: HasDB db => ... -> Action db ...


----------------------------------------------------------------------
-- the downstream library / application does this:

data TBC = -- ...

instance HasDB TBC where
    lookupUser = polyQuery . lookupUser
```

**Comment by mf59816** [comment]
@fhartwig: hey, you destroyed my moprism!  heh...

**Comment by mf59816** [comment]
One more thing to keep in mind: `polyQuery` and `runThentosQuery`, plus the update versions of these functions, are something that the author of `TBC` may also want to have for their library.  There may be need for more `TH` trickery.

But one cool thing that occurred to me: I think this approach even allows you to write a thentos clone that uses both `TBC` and a bunch of other (direct or indirect) `DB` derivatives: You just need to provide more lenses and make a few more mystifying `TH` calls.

**Comment by fhartwig** [comment]
New attempt at a design:

```haskell
----------------------------------------------------------------------
-- the upstream library does this:

-- to be generated by @$(makeHasAcidicClass ''DB transaction_names)@ (or
-- is it easier to pass 'AsDB also / instead?)
class (AsDB db) => HasDB db where
    lookupUser :: UserId -> Action db (UserId, User))
    -- ...

-- to be generated by @$(makeHasAcidicInstance ''DB transaction_names)@
instance HasDB DB where
    lookupUser = query'P . LookupUser
    -- ...

-- then, we can write polymorphic actions:
bumpSession :: HasDB db => ... -> Action db ...


----------------------------------------------------------------------
-- the downstream library / application has to generate it's own transaction types (e.g. LookupUser) using TH functions that we provide (that also generates the HasDB instance?)

data TBC = -- ...

instance HasDB TBC where
    lookupUser = query'P . LookupUser
```

**Comment by mf59816** [comment]
(We also discussed recycling the `LookupUser` event already provided by the upstream library, but the `Method` instance fixes `MethodState` for that event to `DB` for good.  Perhaps there is a non-invasive way to change `acid-state` itself?)

**Comment by mf59816** [comment]
(somewhat related: 2015-06-24-mf-error-type-family)

**Comment by mf59816** [comment]
(@fhartwig's wip for reference: 2015-06-23-fh-poly-transactions)
